// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4ee73dROSd2Yh6cZTmZ7VFGFmBJ62UHM',
    appId: '1:1026041970750:android:8aa4bc5fde53fd90fdd16f',
    messagingSenderId: '1026041970750',
    projectId: 'posts-task-44f4e',
    databaseURL: 'https://posts-task-44f4e-default-rtdb.firebaseio.com',
    storageBucket: 'posts-task-44f4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNklLFK5evLzZC2iOHyajwBCYLXo41pYs',
    appId: '1:1026041970750:ios:5bba55925a3f27f1fdd16f',
    messagingSenderId: '1026041970750',
    projectId: 'posts-task-44f4e',
    databaseURL: 'https://posts-task-44f4e-default-rtdb.firebaseio.com',
    storageBucket: 'posts-task-44f4e.appspot.com',
    iosBundleId: 'com.posts.test.postsTest',
  );
}
